#+title: macOS Setup

* Bootstrap

** Install my SSH and GPG keys

** Fix macOS Sierra =ssh-agent= issue

#+BEGIN_SRC sh
  cat >> ~/.ssh/config <<EOF
  Host *
      IdentityFile ~/.ssh/id_rsa
      AddKeysToAgent yes
  EOF
#+END_SRC

** Clone the dotfiles

#+BEGIN_SRC sh
  mkdir -p ~/Projects
  git clone git@github.com:tungd/dotfiles-lean.git ~/Projects/dotfiles
#+END_SRC

** Making aliases

#+BEGIN_SRC sh
  mkdir -p ~/.local/bin

  ln -s ~/Projects/dotfiles/.bash_profile ~/.bash_profile
  ln -s ~/Projects/dotfiles/.bashrc ~/.bashrc
  ln -s ~/Projects/dotfiles/.emacs.d ~/.emacs.d
  ln -s ~/Projects/dotfiles/.gitconfig ~/.gitconfig
  ln -s ~/Projects/dotfiles/.npmrc ~/.npmrc
  ln -s ~/Projects/dotfiles/.eslintrc ~/.eslintrc
#+END_SRC


* Install apps and utilities

** XCode

#+BEGIN_SRC sh
  xcode-select --install
#+END_SRC

** =macports=

I don't use Homebrew, it is too fragile and invasive for my taste. I tried Nix
but it's not ready for prime time yet. Deal breaker for me is a long standing
issue regarding =watchman= (https://github.com/NixOS/nixpkgs/issues/14309).

I tried =pkgsrc=, it was great but the number of packages are so limited, and
updates were so infrequent. I now settled down with MacPorts. It is simple, pretty
similar to =apt= and =yum=, supports package version pining and has all of the
packages that I need. It's also not updated too frequently like
Homebrew. Installation is a little bit more involved, though.

#+BEGIN_SRC sh
  # the general stuffs
  sudo port install aspell aspell-dict-en automake autoconf openssl htop
  sudo port install kubectl-1.24 terraform-1.2
  sudo port install watchman sqlite3 ripgrep tree libxml2 lcms2
  sudo port install nodejs18 npm8 yarn python3.10 py310-pip py310-awscli postgresql14
  sudo port install texinfo gnutls
  sudo port install z direnv
#+END_SRC

** AWS Session Manager plugin

#+begin_src sh
  cd /tmp
  curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac_arm64/sessionmanager-bundle.zip" -o "sessionmanager-bundle.zip"
  unzip sessionmanager-bundle.zip
  ./sessionmanager-bundle/install -i ~/.local/lib/aws-ssm -b ~/.local/bin/session-manager-plugin
#+end_src

#+begin_src sh
  curl -L https://raw.githubusercontent.com/qoomon/aws-ssm-ec2-proxy-command/master/aws-ssm-ec2-proxy-command.sh -o ~/.local/aws-ssm-ec2-proxy-command.sh
  chmod +x  ~/.local/aws-ssm-ec2-proxy-command.sh
#+end_src

#+begin_src sh
  cat >> ~/.ssh/config <<EOF
  Host i-* mi-*
    IdentityFile ~/.ssh/id_rsa
    ProxyCommand ~/.local/aws-ssm-ec2-proxy-command.sh %h %r %p ~/.ssh/id_rsa.pub
    StrictHostKeyChecking no
  EOF
#+end_src

* System configuration

** Keyboard configuration

Decrease repeat delay, increase repeat rate and disable Emoji.

#+BEGIN_SRC sh
  defaults write -g ApplePressAndHoldEnabled -bool false
  # defaults write -g InitialKeyRepeat -int 10
  defaults write -g KeyRepeat -int 1
  defaults write -g NSUserKeyEquivalents -dict-add 'Emoji & Symbols' '@^j'
#+END_SRC

** No shadow on window capture (Cmd-S-4 SPC)

#+BEGIN_SRC sh
  defaults write com.apple.screencapture disable-shadow -bool true
#+END_SRC

** Disable font-smoothing, works better with 2k external display (provided web pages are zoomed & editors uses medium fonts)

#+begin_src sh
  defaults -currentHost write -g AppleFontSmoothing -int 0
#+end_src
