#+title: macOS Setup

* Bootstrap

** Install my SSH and GPG keys

** Fix macOS Sierra =ssh-agent= issue

#+BEGIN_SRC sh
  cat >> ~/.ssh/config <<EOF
  Host *
      IdentityFile ~/.ssh/id_rsa
      AddKeysToAgent yes
  EOF
#+END_SRC

** Clone the dotfiles

#+BEGIN_SRC sh
  mkdir -p ~/Projects
  git clone git@github.com:tungd/dotfiles-lean.git ~/Projects/dotfiles
#+END_SRC

** Making aliases

#+BEGIN_SRC sh
  mkdir -p ~/.local/bin
  mkdir -p ~/.local/vendor

  ln -s ~/Projects/dotfiles/.bash_profile ~/.bash_profile
  ln -s ~/Projects/dotfiles/.bashrc ~/.bashrc
  ln -s ~/Projects/dotfiles/.emacs.d ~/.emacs.d
  ln -s ~/Projects/dotfiles/.gitconfig ~/.gitconfig
  ln -s ~/Projects/dotfiles/.npmrc ~/.npmrc
  ln -s ~/Projects/dotfiles/.eslintrc ~/.eslintrc
#+END_SRC


* Install apps and utilities

** XCode

#+BEGIN_SRC sh
  xcode-select --install
#+END_SRC

** =macports=

I don't use Homebrew, it is too fragile and invasive for my taste. I tried Nix
but it's not ready for prime time yet. Deal breaker for me is a long standing
issue regarding =watchman= (https://github.com/NixOS/nixpkgs/issues/14309).

I tried =pkgsrc=, it was great but the number of packages are so limited, and
updates were so infrequent. I now settled down with MacPorts. It is simple, pretty
similar to =apt= and =yum=, supports package version pining and has all of the
packages that I need. It's also not updated too frequently like
Homebrew. Installation is a little bit more involved, though.

#+BEGIN_SRC sh
  # the general stuffs
  sudo port install aspell aspell-dict-en automake autoconf openssl htop terraform-0.13
  sudo port install watchman sqlite3 ripgrep tree libxml2 lcms2
  sudo port install nodejs14 npm6 yarn python3.8 py38-pip py38-awscli postgresql12
  sudo port install texinfo gnutls jansson
  sudo port install pinentry-mac
  sudo port install emacs-devel-app +nativecomp -rsvg
#+END_SRC

** ASDF

#+begin_src sh
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
#+end_src

** Poetry

#+begin_src sh
  asdf plugin add poetry
  asdf install poetry latest
#+end_src

** =z.sh=

=z.sh= (https://github.com/rupa/z) allows me to visit one of the directories I
worked on recently by typing just a partial path of it.

#+BEGIN_SRC sh
  curl -L https://raw.githubusercontent.com/rupa/z/master/z.sh > ~/.local/vendor/z.sh
#+END_SRC

** =direnv=

Automatically set environment variable per directory. This is also available
through MacPorts but requires the whole Go installation so I'd still prefer
downloading the binary.

#+BEGIN_SRC sh
  curl -L -o ~/.local/bin/direnv https://github.com/direnv/direnv/releases/download/v2.20.0/direnv.darwin-amd64
  chmod +x ~/.local/bin/direnv
#+END_SRC


* System configuration

** Keyboard configuration

Decrease repeat delay, increase repeat rate and disable Emoji.

#+BEGIN_SRC sh
  defaults write -g ApplePressAndHoldEnabled -bool false
  # defaults write -g InitialKeyRepeat -int 10
  defaults write -g KeyRepeat -int 1
  defaults write -g NSUserKeyEquivalents -dict-add 'Emoji & Symbols' '@^j'
#+END_SRC

** No shadow on window capture (Cmd-S-4 SPC)

#+BEGIN_SRC sh
  defaults write com.apple.screencapture disable-shadow -bool true
#+END_SRC

** Restart the UI Server service to activate the changes

#+BEGIN_SRC sh
  killall SystemUIServer
#+END_SRC

#+begin_src xml
  <key>LIBRARY_PATH</key>
  <string>/opt/local/lib/gcc10:/opt/local/lib/gcc10/gcc/x86_64-apple-darwin20/10.3.0:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib</string>
#+end_src
