#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off

# only display shadows for the floating window
yabai -m config window_shadow                float
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff3366cc
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.62
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# application rules
# Apps that should always be floating
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Installer$" manage=off

yabai -m rule --add app="^iStat Menus$" manage=off
yabai -m rule --add app="^Intel Power Gadget$" manage=off

yabai -m rule --add app="^Mail$" manage=off

# #1 is the free space

# Emacs + iTerm #2
yabai -m rule --add app="^Emacs$" space=2
yabai -m rule --add app="^iTerm2$" space=2

# Safari #3
yabai -m rule --add app="^Safari$" space=3

# Commnucation apps go to the last space
yabai -m rule --add app="^Messenger$" space=4
yabai -m rule --add app="^Slack$" space=4
yabai -m rule --add app="^Mail$" space=4

echo "yabai configuration loaded.."
