PortIndex: editors/emacs-dev/Portfile
	portindex

emacs-dev:
	curl -LO 'https://codeload.github.com/emacs-mirror/emacs/legacy.tar.gz/2b848a4e504319cce150000a2c3855f66d89714b?dummy='
	shasum -a 256 2b848a4e504319cce150000a2c3855f66d89714b
	echo 'Latest revision: '
	echo 'Latest sha: '

.PHONY: emacs-dev PortIndex
