;;; codeberg-dark-theme.el --- Codeberg dark theme -*- lexical-binding: t; -*-

;; Author: Tung Dao
;; URL: https://codeberg.org/Codeberg-Infrastructure/forgejo
;; Package-Requires: ((emacs "27.1"))

;;; Commentary:

;; A dark Emacs theme based on Codeberg's Forgejo dark UI and Chroma syntax
;; colors.

;;; Code:

(deftheme codeberg-dark
  "Dark theme based on Codeberg's Forgejo Chroma colors.")

(let* ((class '((class color) (min-colors 89)))
       (bg "#0c1a24")
       (bg-alt "#04121b")
       (bg-dim "#010609")
       (bg-panel "#061825")
       (bg-active "#1d4057")
       (bg-hover "#304f64")
       (fg "#d4dbdf")
       (fg-code "#c9d1d9")
       (fg-soft "#b6bac5")
       (muted "#8b9da9")
       (muted-2 "#546e80")
       (muted-3 "#425f72")
       (comment "#777e94")
       (orange "#ff7540")
       (orange-2 "#ff8540")
       (yellow "#fabd2f")
       (yellow-2 "#ffaa10")
       (green "#b8bb26")
       (green-2 "#8ec07c")
       (blue "#649bc4")
       (blue-2 "#649bee")
       (purple "#9075cd")
       (red "#ff4433")
       (red-bg "#5f3737")
       (green-bg "#3a523a")
       (selection "#1a6aa6")
       (region-fg "#ffffff"))
  (custom-theme-set-faces
   'codeberg-dark

   ;; Core UI.
   `(default ((,class :foreground ,fg :background ,bg)))
   `(cursor ((,class :background ,yellow-2)))
   `(fringe ((,class :foreground ,muted-2 :background ,bg)))
   `(highlight ((,class :background ,bg-active)))
   `(hl-line ((,class :background ,bg-panel)))
   `(region ((,class :foreground ,region-fg :background ,selection)))
   `(secondary-selection ((,class :foreground ,region-fg :background ,bg-hover)))
   `(shadow ((,class :foreground ,muted-2)))
   `(minibuffer-prompt ((,class :foreground ,yellow :weight bold)))
   `(escape-glyph ((,class :foreground ,orange)))
   `(homoglyph ((,class :foreground ,orange)))
   `(link ((,class :foreground ,blue-2 :underline t)))
   `(link-visited ((,class :foreground ,purple :underline t)))
   `(button ((,class :foreground ,blue-2 :underline t)))
   `(match ((,class :foreground ,bg-dim :background ,yellow)))
   `(lazy-highlight ((,class :foreground ,bg-dim :background ,green)))
   `(isearch ((,class :foreground ,bg-dim :background ,yellow-2 :weight bold)))
   `(isearch-fail ((,class :foreground ,region-fg :background ,red-bg)))
   `(show-paren-match ((,class :foreground ,bg-dim :background ,green-2 :weight bold)))
   `(show-paren-mismatch ((,class :foreground ,region-fg :background ,red :weight bold)))
   `(trailing-whitespace ((,class :background ,red-bg)))
   `(vertical-border ((,class :foreground ,muted-3)))
   `(window-divider ((,class :foreground ,muted-3)))
   `(window-divider-first-pixel ((,class :foreground ,muted-3)))
   `(window-divider-last-pixel ((,class :foreground ,muted-3)))
   `(tooltip ((,class :foreground ,fg :background ,bg-active)))
   `(error ((,class :foreground ,red)))
   `(warning ((,class :foreground ,yellow-2)))
   `(success ((,class :foreground ,green-2)))

   ;; Mode line.
   `(mode-line ((,class :foreground ,fg :background ,bg-active :box (:line-width -1 :color ,bg-hover))))
   `(mode-line-inactive ((,class :foreground ,muted :background ,bg-panel :box (:line-width -1 :color ,bg-panel))))
   `(mode-line-buffer-id ((,class :foreground ,yellow :weight bold)))
   `(header-line ((,class :foreground ,fg :background ,bg-panel)))
   `(tab-line ((,class :foreground ,muted :background ,bg-dim)))
   `(tab-line-tab ((,class :foreground ,fg :background ,bg-active)))
   `(tab-line-tab-current ((,class :foreground ,yellow :background ,bg-active :weight bold)))
   `(tab-line-tab-inactive ((,class :foreground ,muted :background ,bg-panel)))

   ;; Line numbers and margins.
   `(line-number ((,class :foreground ,muted-3 :background ,bg)))
   `(line-number-current-line ((,class :foreground ,yellow :background ,bg-panel)))
   `(fill-column-indicator ((,class :foreground ,muted-3)))

   ;; Font lock, mapped from Codeberg/Forgejo Chroma dark.css.
   `(font-lock-builtin-face ((,class :foreground ,yellow)))
   `(font-lock-comment-face ((,class :foreground ,comment :slant normal)))
   `(font-lock-comment-delimiter-face ((,class :foreground ,comment :slant normal)))
   `(font-lock-constant-face ((,class :foreground ,blue)))
   `(font-lock-doc-face ((,class :foreground ,green :slant normal)))
   `(font-lock-doc-markup-face ((,class :foreground ,green-2)))
   `(font-lock-function-call-face ((,class :foreground ,fg-code)))
   `(font-lock-function-name-face ((,class :foreground ,yellow)))
   `(font-lock-keyword-face ((,class :foreground ,orange)))
   `(font-lock-negation-char-face ((,class :foreground ,orange)))
   `(font-lock-number-face ((,class :foreground ,blue)))
   `(font-lock-operator-face ((,class :foreground ,orange)))
   `(font-lock-preprocessor-face ((,class :foreground ,green-2)))
   `(font-lock-property-name-face ((,class :foreground ,fg-soft)))
   `(font-lock-property-use-face ((,class :foreground ,fg-soft)))
   `(font-lock-punctuation-face ((,class :foreground "#d2d4db")))
   `(font-lock-regexp-grouping-backslash ((,class :foreground ,purple)))
   `(font-lock-regexp-grouping-construct ((,class :foreground ,purple)))
   `(font-lock-string-face ((,class :foreground ,green :slant normal)))
   `(font-lock-type-face ((,class :foreground ,yellow-2)))
   `(font-lock-variable-name-face ((,class :foreground "#ebdbb2")))
   `(font-lock-variable-use-face ((,class :foreground ,fg-code)))
   `(font-lock-warning-face ((,class :foreground ,red :weight bold)))

   ;; Search, completion, minibuffer.
   `(completions-annotations ((,class :foreground ,comment)))
   `(completions-common-part ((,class :foreground ,yellow :weight bold)))
   `(completions-first-difference ((,class :foreground ,orange :weight bold)))
   `(completions-highlight ((,class :inherit region)))
   `(icomplete-first-match ((,class :foreground ,yellow :weight bold)))
   `(match ((,class :foreground ,bg-dim :background ,yellow)))

   ;; Dired.
   `(dired-directory ((,class :foreground ,blue-2 :weight bold)))
   `(dired-flagged ((,class :foreground ,red)))
   `(dired-header ((,class :foreground ,yellow :weight bold)))
   `(dired-ignored ((,class :foreground ,muted-2)))
   `(dired-mark ((,class :foreground ,yellow)))
   `(dired-marked ((,class :foreground ,orange)))
   `(dired-perm-write ((,class :foreground ,fg)))
   `(dired-symlink ((,class :foreground ,purple)))
   `(dired-warning ((,class :foreground ,red)))

   ;; Diff and VC.
   `(diff-added ((,class :foreground ,green-2 :background ,green-bg)))
   `(diff-changed ((,class :foreground ,yellow-2 :background ,bg-active)))
   `(diff-removed ((,class :foreground ,red :background ,red-bg)))
   `(diff-refine-added ((,class :foreground ,region-fg :background "#476b47")))
   `(diff-refine-changed ((,class :foreground ,region-fg :background "#705a22")))
   `(diff-refine-removed ((,class :foreground ,region-fg :background "#7a3b3b")))
   `(diff-header ((,class :foreground ,fg :background ,bg-panel)))
   `(diff-file-header ((,class :foreground ,yellow :background ,bg-active :weight bold)))
   `(diff-hunk-header ((,class :foreground ,blue :background ,bg-panel)))
   `(diff-context ((,class :foreground ,fg-code)))
   `(diff-indicator-added ((,class :foreground ,green-2)))
   `(diff-indicator-changed ((,class :foreground ,yellow-2)))
   `(diff-indicator-removed ((,class :foreground ,red)))
   `(vc-conflict-state ((,class :foreground ,red)))
   `(vc-edited-state ((,class :foreground ,yellow-2)))
   `(vc-locally-added-state ((,class :foreground ,green-2)))
   `(vc-locked-state ((,class :foreground ,orange)))
   `(vc-missing-state ((,class :foreground ,red)))
   `(vc-needs-update-state ((,class :foreground ,orange)))
   `(vc-removed-state ((,class :foreground ,red)))
   `(vc-up-to-date-state ((,class :foreground ,green-2)))

   ;; Org.
   `(org-agenda-date ((,class :foreground ,blue-2)))
   `(org-agenda-date-today ((,class :foreground ,yellow :weight bold)))
   `(org-agenda-date-weekend ((,class :foreground ,purple)))
   `(org-block ((,class :foreground ,fg-code :background ,bg-alt)))
   `(org-block-begin-line ((,class :foreground ,comment :background ,bg-panel)))
   `(org-block-end-line ((,class :foreground ,comment :background ,bg-panel)))
   `(org-code ((,class :foreground ,green)))
   `(org-date ((,class :foreground ,blue-2 :underline t)))
   `(org-document-info ((,class :foreground ,fg)))
   `(org-document-title ((,class :foreground ,yellow :weight bold :height 1.2)))
   `(org-done ((,class :foreground ,green-2 :weight bold)))
   `(org-headline-done ((,class :foreground ,muted-2)))
   `(org-hide ((,class :foreground ,bg)))
   `(org-level-1 ((,class :foreground ,yellow :weight bold :height 1.15)))
   `(org-level-2 ((,class :foreground ,blue-2 :weight bold :height 1.08)))
   `(org-level-3 ((,class :foreground ,orange :weight bold)))
   `(org-level-4 ((,class :foreground ,green-2 :weight bold)))
   `(org-level-5 ((,class :foreground ,purple)))
   `(org-level-6 ((,class :foreground ,blue)))
   `(org-link ((,class :foreground ,blue-2 :underline t)))
   `(org-meta-line ((,class :foreground ,comment)))
   `(org-quote ((,class :foreground ,fg-soft :slant italic)))
   `(org-special-keyword ((,class :foreground ,comment)))
   `(org-table ((,class :foreground ,blue)))
   `(org-tag ((,class :foreground ,muted :weight normal)))
   `(org-todo ((,class :foreground ,orange :weight bold)))
   `(org-verbatim ((,class :foreground ,green)))

   ;; Markdown.
   `(markdown-code-face ((,class :foreground ,fg-code :background ,bg-alt)))
   `(markdown-header-face ((,class :foreground ,yellow :weight bold)))
   `(markdown-header-face-1 ((,class :foreground ,yellow :weight bold :height 1.15)))
   `(markdown-header-face-2 ((,class :foreground ,blue-2 :weight bold :height 1.08)))
   `(markdown-header-face-3 ((,class :foreground ,orange :weight bold)))
   `(markdown-inline-code-face ((,class :foreground ,green)))
   `(markdown-link-face ((,class :foreground ,blue-2 :underline t)))
   `(markdown-pre-face ((,class :foreground ,fg-code :background ,bg-alt)))

   ;; Whitespace.
   `(whitespace-empty ((,class :background ,red-bg)))
   `(whitespace-hspace ((,class :foreground ,muted-3)))
   `(whitespace-indentation ((,class :foreground ,muted-3)))
   `(whitespace-line ((,class :background ,bg-panel)))
   `(whitespace-newline ((,class :foreground ,muted-3)))
   `(whitespace-space ((,class :foreground ,muted-3)))
   `(whitespace-space-after-tab ((,class :background ,red-bg)))
   `(whitespace-space-before-tab ((,class :background ,red-bg)))
   `(whitespace-tab ((,class :foreground ,muted-3)))
   `(whitespace-trailing ((,class :background ,red-bg)))

   ;; Common packages.
   `(avy-lead-face ((,class :foreground ,bg-dim :background ,yellow :weight bold)))
   `(avy-lead-face-0 ((,class :foreground ,bg-dim :background ,blue :weight bold)))
   `(avy-lead-face-1 ((,class :foreground ,bg-dim :background ,purple :weight bold)))
   `(avy-lead-face-2 ((,class :foreground ,bg-dim :background ,green :weight bold)))
   `(consult-highlight-match ((,class :inherit match)))
   `(consult-preview-match ((,class :inherit region)))
   `(eglot-highlight-symbol-face ((,class :background ,bg-active :weight normal)))
   `(eglot-inlay-hint-face ((,class :foreground ,comment :background ,bg :height 1.0)))
   `(flymake-error ((,class :underline (:style wave :color ,red))))
   `(flymake-note ((,class :underline (:style wave :color ,blue))))
   `(flymake-warning ((,class :underline (:style wave :color ,yellow-2))))
   `(magit-branch-current ((,class :foreground ,blue-2 :box t)))
   `(magit-branch-local ((,class :foreground ,blue-2)))
   `(magit-branch-remote ((,class :foreground ,green-2)))
   `(magit-diff-added ((,class :foreground ,green-2 :background ,green-bg)))
   `(magit-diff-added-highlight ((,class :foreground ,green-2 :background "#314a37")))
   `(magit-diff-context ((,class :foreground ,fg-code :background ,bg)))
   `(magit-diff-context-highlight ((,class :foreground ,fg-code :background ,bg-panel)))
   `(magit-diff-file-heading ((,class :foreground ,yellow :weight bold)))
   `(magit-diff-file-heading-highlight ((,class :background ,bg-panel)))
   `(magit-diff-hunk-heading ((,class :foreground ,blue :background ,bg-panel)))
   `(magit-diff-hunk-heading-highlight ((,class :foreground ,blue :background ,bg-active)))
   `(magit-diff-removed ((,class :foreground ,red :background ,red-bg)))
   `(magit-diff-removed-highlight ((,class :foreground ,red :background "#634343")))
   `(magit-hash ((,class :foreground ,comment)))
   `(magit-section-heading ((,class :foreground ,yellow :weight bold)))
   `(magit-section-highlight ((,class :background ,bg-panel)))
   `(which-key-command-description-face ((,class :foreground ,yellow)))
   `(which-key-group-description-face ((,class :foreground ,blue-2)))
   `(which-key-key-face ((,class :foreground ,green-2 :weight bold)))
   `(which-key-separator-face ((,class :foreground ,comment)))))

(provide-theme 'codeberg-dark)

;;; codeberg-dark-theme.el ends here
