;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from adaptive-font-size-mode.el

(autoload 'adaptive-font-size-adapt "adaptive-font-size-mode"
"Set font size based on monitor PPI for FRAME (or current frame).

(fn &optional FRAME)")
(defvar adaptive-font-size-mode nil
"Non-nil if Adaptive-Font-Size mode is enabled.
See the `adaptive-font-size-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `adaptive-font-size-mode'.")
(custom-autoload 'adaptive-font-size-mode "adaptive-font-size-mode" nil)
(autoload 'adaptive-font-size-mode "adaptive-font-size-mode"
"Toggle Adaptive Font Mode.

When enabled, this global minor mode adjusts the default font
size based on the screen's PPI when focus changes or a new frame
is created.

This is a global minor mode.  If called interactively, toggle the
`Adaptive-Font-Size mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='adaptive-font-size-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)


;;; Generated autoloads from auto-dark-mode.el

(autoload 'auto-dark-adapt "auto-dark-mode"
"Detect system appearance and switch theme accordingly for FRAME (or current frame).

(fn &optional FRAME)")
(defvar auto-dark-mode nil
"Non-nil if Auto-Dark mode is enabled.
See the `auto-dark-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `auto-dark-mode'.")
(custom-autoload 'auto-dark-mode "auto-dark-mode" nil)
(autoload 'auto-dark-mode "auto-dark-mode"
"Toggle Auto Dark Mode.

When enabled, this global minor mode detects the system's
dark/light mode setting and switches the Emacs theme
accordingly when focus changes.

This is a global minor mode.  If called interactively, toggle the
`Auto-Dark mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='auto-dark-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "auto-dark-mode" '("auto-dark-"))


;;; Generated autoloads from citre-raven.el

(autoload 'citre-raven-create-tags-file "citre-raven"
"Create a Citre-compatible tags file for the current project using Raven.

(fn &optional SYNC)" t)
(autoload 'citre-raven-update-this-tags-file "citre-raven"
"Update the current Citre tags file using Raven.

(fn &optional SYNC)" t)
(register-definition-prefixes "citre-raven" '("citre-raven-"))


;;; Generated autoloads from expreg.el

(autoload 'expreg-expand "expreg"
"Expand region." t)
(autoload 'expreg-contract "expreg"
"Contract region." t)
(register-definition-prefixes "expreg" '("expreg-"))


;;; Generated autoloads from gptel-cloudflare-ai-gateway.el

(autoload 'gptel-cloudflare-ai-gateway-api-key "gptel-cloudflare-ai-gateway"
"Return the Cloudflare AI Gateway API key from auth-source.")
(autoload 'gptel-cloudflare-ai-gateway-setup "gptel-cloudflare-ai-gateway"
"Set up gptel to use Cloudflare AI Gateway.")
(register-definition-prefixes "gptel-cloudflare-ai-gateway" '("gptel-cloudflare-ai-gateway-"))


;;; Generated autoloads from mql-mode.el

(autoload 'mql-mode "mql-mode"
"Major mode for editing MetaTrader MQL4/5 code.

In addition to any hooks its parent mode `c-mode' might have run, this
mode runs the hook `mql-mode-hook', as the final or penultimate step
during initialization.

\\{mql-mode-map}" t)
(add-to-list 'auto-mode-alist '("\\.mq4\\'" . mql-mode))
(register-definition-prefixes "mql-mode" '("mql-"))


;;; Generated autoloads from ob-http.el

(autoload 'td-ob-http-cancel-at-point "ob-http"
"Cancel the in-flight HTTP request for the Org source block at point." t)
(autoload 'td-ob-http-copy-as-curl "ob-http"
"Copy current Org HTTP source block as a curl command." t)
(autoload 'td-ob-http-copy-as-fetch "ob-http"
"Copy current Org HTTP source block as a JavaScript fetch snippet." t)
(autoload 'td-ob-http-copy-as-python "ob-http"
"Copy current Org HTTP source block as a Python requests snippet." t)
(autoload 'td-ob-http-export-postman-collection "ob-http"
"Export HTTP source blocks in the current Org buffer to Postman FILE.

With prefix NAME, prompt for the collection name.

(fn FILE &optional NAME)" t)
(autoload 'td-ob-http-import-postman-collection "ob-http"
"Insert Postman collection FILE into the current Org buffer.

(fn FILE)" t)
(register-definition-prefixes "ob-http" '("org-babel-" "td-ob-http-"))


;;; Generated autoloads from opam-env-mode.el

(autoload 'opam-env-refresh "opam-env-mode"
"Force refresh OPAM environment for current buffer context." t)
(autoload 'opam-env-select-switch "opam-env-mode"
"Interactively select SWITCH for the current project and apply its OPAM env.

(fn SWITCH)" t)
(autoload 'opam-env-clear-switch-override "opam-env-mode"
"Clear the session switch override for the current project and refresh." t)
(defvar opam-env-mode nil
"Non-nil if Opam-Env mode is enabled.
See the `opam-env-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `opam-env-mode'.")
(custom-autoload 'opam-env-mode "opam-env-mode" nil)
(autoload 'opam-env-mode "opam-env-mode"
"Global minor mode to keep OPAM environment aligned with OCaml projects.

This is a global minor mode.  If called interactively, toggle the
`Opam-Env mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='opam-env-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "opam-env-mode" '("opam-env-"))


;;; Generated autoloads from sql-clickhouse.el

(autoload 'sql-clickhouse "sql-clickhouse"
"Run clickhouse-client by ClickHouse as an inferior process.
Optional argument BUFFER current buffer.

(fn &optional BUFFER)" t)
(register-definition-prefixes "sql-clickhouse" '("sql-clickhouse-"))


;;; Generated autoloads from scv.el

(autoload 'scv-session-manager "scv"
"Open the scv Session Manager." t)
(autoload 'scv-open-prompt-draft "scv"
"Open the Rich Prompt Box for SESSION-ID and ORIGIN.

(fn &optional SESSION-ID ORIGIN)" t)
(autoload 'scv-open-session-viewer "scv"
"Open a native Emacs Session Viewer for SESSION-ID and ORIGIN.

(fn SESSION-ID &optional ORIGIN)" t)
(autoload 'scv-new-session "scv"
"Start a new local Session Viewer.

With PROMPT-FOR-ID, prompt for the Session id instead of using a generated id.

(fn &optional PROMPT-FOR-ID)" t)
(autoload 'scv-menu "scv"
"Open the scv transient command menu." t)
(autoload 'scv-install "scv"
"Attach scv key bindings to LEADER-MAP under KEY.

KEY defaults to \"S\".

(fn LEADER-MAP &optional KEY)")
(register-definition-prefixes "scv" '("scv-"))


;;; Generated autoloads from scv-reducer.el

(register-definition-prefixes "scv-reducer" '("scv-reducer-"))


;;; Generated autoloads from scv-reducer-tests.el

(register-definition-prefixes "scv-reducer-tests" '("scv-"))


;;; Generated autoloads from scv-session-viewer.el

(autoload 'scv-session-viewer-open "scv-session-viewer"
"Open native Emacs Session Viewer for SESSION-ID.

(fn SESSION-ID)" t)
(autoload 'scv-session-viewer-close "scv-session-viewer"
"Close current Session Viewer." t)
(register-definition-prefixes "scv-session-viewer" '("scv-session-viewer-"))


;;; Generated autoloads from scv-session-viewer-tests.el

(register-definition-prefixes "scv-session-viewer-tests" '("scv-test-"))


;;; Generated autoloads from scv-tests.el

(register-definition-prefixes "scv-tests" '("scv-test--w"))


;;; Generated autoloads from prism.el

(autoload 'prism-soften-theme-faces "prism"
"Walk all defined faces and soften contrast.

(fn &rest _)" t)
(provide 'prism)
(register-definition-prefixes "prism" '("prism-"))


;;; Generated autoloads from prism-tests.el

(register-definition-prefixes "prism-tests" '("prism--test-hex->rgb"))


;;; Generated autoloads from ob-excalidraw.el

(autoload 'ob-excalidraw-setup "ob-excalidraw"
"Set up ob-excalidraw by advising org-edit-src-code.
This intercepts C-c ' for excalidraw blocks and launches the
visual editor instead." t)
(autoload 'ob-excalidraw-teardown "ob-excalidraw"
"Remove the ob-excalidraw advice from org-edit-src-code." t)
(register-definition-prefixes "ob-excalidraw" '("ob-excalidraw-" "org-babel-"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
